services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${MONOLITH_DB_NAME}
    ports:
      - "1234:5432"
    networks:
      - eva
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolith-api
    ports:
      - "8000:8080"
    networks:
      - eva
    depends_on:
      - db
    restart: always

networks:
  eva:
    driver: bridge
